name: Laravel Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ["8.3"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Dump Autoload
        run: composer dump-autoload

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test
